### ISSUE TITLE
Convert boolean internal functions returning an integer to returning a bool

### ISSUE THREAD

**Issue by rinon** [immunant/rexpat#23]

**Comment by thedataking** [comment]
Note: perhaps this is obvious to others, but I think there is an opportunity to develop a "boolificaton" refactoring since changing the types from `c_int`s (with non-zero representing true) to Rust's native bool leaves the code that needs rewriting like so:

- `$expr != 0` simply becomes `$expr`, and
- `$expr == 0` becomes `!$expr`.

**Comment by thedataking** [comment]
Closed in 784e1d11262bb0aae43ef424a96002a19775ccb9.
